### PR TITLE
Issue 400

### PR DESCRIPTION
**Pull request by theKashey**
## Summary
Track the loading state for `isReady`, should solve #400 

The logic so:
- there is no `__webpack_modules__[key]` - load async
- there is `__webpack_modules__[key]` - load sync, only if you are still not loading async

In other words - don't load while you load.

## Test plan

Hard to reproduce, you have to load component, which would require more than one chunk to load, and the first one to be loaded before second.

### CODE REVIEW

**Comment by foglerek** [comment]
@neoziro Do you think this approach is going to end up getting merged in, or are you planning on waiting on webpack to expose a more reliable sync-load method?

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
`loading` was not the best name, as long as in case of failed loading it would be still `loading`, while it does nothing.
As a result, it was replaced by `resolved`

**Comment by iamstarkov** [comment]
@theKashey should the tests be fixed?

**Comment by theKashey** [comment]
Sorry, forgot to push updated snapshots

**Comment by theKashey** [comment]
@neoziro - only you can merge and publish

**Comment by mschipperheyn** [comment]
@neoziro @theKashey any chance this can get merged soonish? The main disadvantage for monorepos is that you can't install directly by git commit.

**Comment by ilyaagarkov** [comment]
Hi everyone!
@neoziro @theKashey Any updates?

**Pull request merged**
