### PR TITLE
Improve lodash imports to reduce size of serverless bundles

### PR DESCRIPTION
**Pull request by luisherranz**
## Summary

Serverless is becoming popular and bundle size is important. This PR avoids importing the whole lodash code, even in the server.

## Test plan

Tests pass for `ChunkExtractor.js`, the only affected file.

### CODE REVIEW

**Comment by neoziro** [comment]
I like that, thanks @luisherranz!

**Comment by luisherranz** [comment]
That was fast. Thanks @neoziro! :)

**Comment by luisherranz** [comment]
@bitttttten it works if you build your bundle using [webpack](https://webpack.js.org/) or [ncc](https://github.com/zeit/ncc) but I agree that maybe adding them as packages may cover more cases.

**Comment by bitttttten** [comment]
Ohh I see. I am not using webpack to bundle my lambdas! To be honest I didn't ever think of doing that. I guess that answers my question, thanks!

If you bundle your lambda with webpack, then wouldn't you loose all the niceties of the console editor? Or does it some how keep all that?

**Comment by luisherranz** [comment]
I'm not familiar with AWS because I use other service. If code don't need to be bundled, then maybe it's not a good idea to make it necessary if someone is using loadable component.

Could you please describe what is the normal workflow in AWS?

**Comment by ScriptedAlchemy** [comment]
use webpack alias to resolve dependencies

**Comment by theKashey** [comment]
use webpack [externals](https://www.npmjs.com/package/webpack-node-externals) to keep `node_modules` in `node_modules`

**Comment by ScriptedAlchemy** [comment]
Can you run require on a lambda? And require node modules on that side?

**Comment by theKashey** [comment]
Of course, you can. Majority of lambdas(they were not created just for SSR task) are written in pure `nodejs`, and haven't ever experienced any bundler.

**Pull request merged**
