### PR TITLE
Babel plugin: prefer import than a variable name

### LINKED ISSUE #128: Server side rendering have no effect in 3.0.x
Hi!
I have writen a ssr demo using `2.2.3`,[here](https://github.com/code-mcx/react-ssr/tree/webpack3.x) is my demo.
Now i want to upgrade `loadable-components` from `2.2.3` to `3.0.x`,only a few things have been done

1. Upgrade babel to 7.x.
2. Replace all `import Loadable from "loadable-components";` with `import Loadable from "@loadable/component";`.
3. Replace babel plugin `loadable-components/babel` with `"@loadable/babel-plugin"`.
4. Using dynamic mode in `src/server.js` replace old api

.

`server.js`
```js
const ReactDOMServer = require("react-dom/server");
const { LoadableState } = require("@loadable/server");
// ...

let component = createApp(context, req.url, store);

const loadableState = new LoadableState();
const loadableComponent = loadableState.collectChunks(component);
// ...

let html = ReactDOMServer.renderToString(loadableComponent);

let htmlStr = template
    // some code
    .replace("<!--react-ssr-outlet-->", 
    `<div id='app'>${html}</div>\n${loadableState.getScriptTags()}`);
```

After call `ReactDOMServer.renderToString()`,i call `loadableState.getScriptTags()`,but return `<script>window.__LOADABLE_STATE__ = [];</script>`

Thanks

### PR DESCRIPTION
**Pull request by bertho-zero**
Should fix #128

### CODE REVIEW

**Comment by neoziro** [comment]
Hello @bertho-zero, thank for you work, but I prefer to rely on using explicitely `loadable`. Then you could choose to use `import loadable from 'something'` and it will work. It is the same strategy used by styled-components and emotion, so let's stick to it.

**Comment by bertho-zero** [comment]
styled-components uses the require, not a variable name that can be used anywhere. (https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/assignStyledRequired.js#L7)

emotion uses the import, as I did here. (https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/index.js#L65)

**Comment by bertho-zero** [comment]
`import loadable from 'something'`

It will not be used like that, when is it useful to use the loadable-components babel plugin with another package?
But we may want to name his variable as we want and that's normal.

**Comment by bertho-zero** [comment]
I can add an option to choose the name of the package to use, is it a good compromise?

**Comment by neoziro** [comment]
I prefer to keep it simple for now, I don't understand why naming it "loadable" is a problem?

**Comment by bertho-zero** [comment]
The babel plugin may be easier to code but it does not reflect the expected use of a babel plugin.

Why go through the AST if it is to do the equivalent of a `.replace`?

This is a plugin that should apply to imports of `@loadable/component` but instead it reserves a function name. I do not understand logic at all.

**Comment by neoziro** [comment]
I want to ensure convention, by doing so you can import loadable from a pre-configured wrapper.

```
import rawLoadable from '@loadable/component'

export const loadable = func => rawLoadable(func, { fallback: 'Loading...' })
```

And it will work, you can't with your method. I think this is why `styled-components` and `emotion` are using this strategy too.

**Pull request closed without merging**
